apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
    release: "{{ .Chart.Name }}"
    heritage: {{ .Release.Service }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  APP_ENVIRONMENT: {{ .Values.config.APP_ENVIRONMENT }}
  BUILD_VERSION: {{ .Values.config.BUILD_VERSION }}
  DB_DATA_SOURCE: "{{ .Values.config.DB_DATA_SOURCE }}"
  DB_INITIAL_CATALOG: "{{ .Values.config.DB_INITIAL_CATALOG }}"
  DB_USER_ID: {{ .Values.config.DB_USER_ID }}
  SERILOG__WRITETO__0__ARGS__SERVERURL: "{{ .Values.config.SERILOG__WRITETO__0__ARGS__SERVERURL }}"
  COMMUNICATION__RABBITMQ__HOST: "{{ .Values.config.COMMUNICATION__RABBITMQ__HOST }}"
  COMMUNICATION__RABBITMQ__PORT: "{{ .Values.config.COMMUNICATION__RABBITMQ__PORT }}"
  COMMUNICATION__RABBITMQ__USERNAME: {{ .Values.config.COMMUNICATION__RABBITMQ__USERNAME }}